@BASE_URL = http://localhost:3000


Get {{BASE_URL}}
###
GET {{BASE_URL}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MGI5YWI3YmNkMWJmYTI0ODdjY2UiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcxOTk5NTUxMywiZXhwIjoxNzE5OTk5MTEzfQ.g5EdbuMVt-6Ozw2XPRpGOx6kOvG0dsDt16Jx0aC4dOY
###
GET {{BASE_URL}}/api/users/66850b8fb7bcd1bfa2487ccc
###
POST  {{BASE_URL}}/api/users/
Content-Type: application/json

{
    "name": "test23",
    "email": "test23@gmail.com",
    "userName": "test23",
    "password" : "123456"
}
###
POST  {{BASE_URL}}/api/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password" : "123456"
}
###
PATCH {{BASE_URL}}/api/users/66850b8fb7bcd1bfa2487ccc
Content-Type: application/json

{
    "name": "deneme@gmail.com"
}
###
PATCH {{BASE_URL}}/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MGI5YWI3YmNkMWJmYTI0ODdjY2UiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcxOTk5NTUxMywiZXhwIjoxNzE5OTk5MTEzfQ.g5EdbuMVt-6Ozw2XPRpGOx6kOvG0dsDt16Jx0aC4dOY


{
    "name": "murat"
}

###
DELETE  {{BASE_URL}}/api/users/66850b8fb7bcd1bfa2487ccc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MGI5YWI3YmNkMWJmYTI0ODdjY2UiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcxOTk5NTUxMywiZXhwIjoxNzE5OTk5MTEzfQ.g5EdbuMVt-6Ozw2XPRpGOx6kOvG0dsDt16Jx0aC4dOY
###
DELETE  {{BASE_URL}}/api/users/deleteAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MGI5YWI3YmNkMWJmYTI0ODdjY2UiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcxOTk5NTUxMywiZXhwIjoxNzE5OTk5MTEzfQ.g5EdbuMVt-6Ozw2XPRpGOx6kOvG0dsDt16Jx0aC4dOY
###
DELETE  {{BASE_URL}}/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg1MGI5YWI3YmNkMWJmYTI0ODdjY2UiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcxOTk5NTUxMywiZXhwIjoxNzE5OTk5MTEzfQ.g5EdbuMVt-6Ozw2XPRpGOx6kOvG0dsDt16Jx0aC4dOY